//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TestingMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Testing";
        public override string RosMessageName => k_RosMessageName;

        public long height;

        public TestingMsg()
        {
            this.height = 0;
        }

        public TestingMsg(long height)
        {
            this.height = height;
        }

        public static TestingMsg Deserialize(MessageDeserializer deserializer) => new TestingMsg(deserializer);

        private TestingMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.height);
        }

        public override string ToString()
        {
            return "TestingMsg: " +
            "\nheight: " + height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
